apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: www
        emptyDir: {}
      - name: wp-config
        configMap:
          name: wp-config
          items:
            - key: wp-config.php
              path: wp-config.php  
      initContainers:
      - name: init
        image: maksymblinov/init_db:v1
        volumeMounts:
        - name: www
          mountPath: /var/www/html
        - name: wp-config
          mountPath: /var/www/html/wp-config.php  
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql-wpmax.mysql.database.azure.com"
        - name: WORDPRESS_DB_NAME
          value: "test_manifest12"
        - name: WORDPRESS_DB_USER
          value: "mysqladmin@mysql-wpmax"
        - name: WORDPRESS_DB_PASSWORD
          value: "1-qwerty"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /var/www/html
        - name: wp-config
          mountPath: /var/www/html/wp-config.php  
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
