name: test

on:
  push:
    branches:
      - main
    

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello
      run: echo "Hello"

    - name: Clon Rep
      uses: actions/checkout@v1

    - name: Printing Deployment  package
      run: ls -al



  terraform:
    runs-on: ubuntu-latest
    needs: [first_job]

    steps:
    - name: terraform plan
      run: terraform plan


