name: test

on:
  push:
    branches:
      - main
    

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello
      run: echo "Hello"

    - name: Print Execute
      run: |
        echo "hello3"
        echo "hello4"
        echo "hello5"




  second_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello2
      run: echo "Hello2"
