name: test

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      TFAction:
        description: "Terraform Action- Apply or Destroy"     
        required: true
        default: "apply"    

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform:
    
    runs-on: ubuntu-latest
    steps:
    - name: Clon Rep
      uses: actions/checkout@v1


    - name: terraform init
      run: terraform init

    - name: 'Az CLI login using OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: terraform plan
      id: plan
      run: terraform plan

    - name: terraform apply
      if: ${{ inputs.TFAction == 'apply'}}
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: ${{ inputs.TFAction == 'destroy' }}
      run: terraform destroy -input=false -auto-approve




