name: test

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

# env:
#       client-id: ${{ secrets.AZURE_CLIENT_ID }}
#       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      

jobs:
  terraform:
    
    runs-on: ubuntu-latest
    steps:
    - name: Clon Rep
      uses: actions/checkout@v1

    

    - name: 'Az CLI login using OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       

    - name: terraform init
      run: terraform init



    - name: terraform plan
      id: plan
      run: terraform plan

    - name: terraform appl
      if: "!contains(github.event.head_commit.message, 'destroy')"
      run: terraform apply -auto-approve


    - name: Terraform Destroy
      if: contains(github.event.head_commit.message, 'destroy')
      run: terraform destroy -auto-approve




