name: test
env:
    client-id: ${{ secrets.AZURE_CLIENT_ID }}
    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
on:
  push:
    branches:
      - main
    

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello
      run: echo "Hello"

    
    - name: Printing Deployment  package
      run: ls -al



  terraform:
    runs-on: ubuntu-latest
    needs: [first_job]

    steps:
    - name: Clon Rep
      uses: actions/checkout@v1

    - name: terraform init
      run: terraform init

    - name: terraform plan
      run: terraform plan


