name: test
env:
    client-id: ${{ secrets.AZURE_CLIENT_ID }}
    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
on:
  push:
    branches:
      - main
    

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Clon Rep
      uses: actions/checkout@v1

    - name: az
      run: az --version

    - name: terraform init
      run: terraform init

    - name: terraform plan
      run: terraform plan


