name: test
on:
  push:
    branches:
      - main
env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: terraform-azure/scripts

    steps:
    - name: Clon Rep
      uses: actions/checkout@v1  

    - name: Copy script files
      uses: actions/upload-artifact@v3
      with:
        name: script-files
        path: ./terraform-azure/scripts/

    - name: Download script files
      uses: actions/download-artifact@v3
      with:
        name: script-files

    - name: Display structure of downloaded files
      run: ls -R    
    

    - name: test script
      env:
        SCRIPT_DIR: ${{ github.workspace }}/terraform-azure/scripts
      run: bash -n $SCRIPT_DIR/create_storage.sh


    


    # - name: terraform init
    #   run: terraform init

    # - name: terraform plan
    #   id: plan
    #   run: terraform plan
      
    # - name: terraform apply
    #   if: "!contains(github.event.head_commit.message, 'destroy')"
    #   run: terraform apply -auto-approve

    # - name: Terraform Destroy
    #   if: contains(github.event.head_commit.message, 'destroy')
    #   run: terraform destroy -auto-approve
      




