name: test2

on:
  push:
    branches:
      - main
    

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello
      run: echo "Hello9"

    - name: Print Execute
      run: |
        echo "hello6"
        echo "hello7"
        echo "hello8"




  second_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello2
      run: echo "Hello10"
