name: test

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform:
    
    runs-on: ubuntu-latest
    steps:
    - name: Clon Rep
      uses: actions/checkout@v1


    - name: terraform init
      run: terraform init

    - name: az login
      run: az login --tenant [tenant-id]

    - name: terraform plan
      id: plan
      run: terraform plan


