name: test

on:
  push:
    branches:
      - main
    

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello
      run: echo "Hello"
      
  second_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello2
      run: echo "Hello2"
