name: test

on:
  push:
    branches:
      - main
    

jobs:
  first_job:
    runs-on: ubuntu-lates

    steps:
    - name: Print Hello
      run: echo "Hello"

    - name: Clon Rep
      uses: actions/checkout@v1

    - name: Printing Deployment  package
      run: ls -al



  second_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello2
      run: echo "Hello2"
