name: test
env:
    client-id: ${{ secrets.AZURE_CLIENT_ID }}
    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    resource_group_name : "aks_tf_test"
    location            : "EastUS2"
    cluster_name        : "devops-test-aks"
    kubernetes_version  : "1.24.9"
    system_node_count   : 2
on:
  push:
    branches:
      - main
    

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello
      run: echo "Hello"

    
    - name: Printing Deployment  package
      run: ls -al



  terraform:
    runs-on: ubuntu-latest
    needs: [first_job]

    steps:
    - name: Clon Rep
      uses: actions/checkout@v1

    - name: terraform plan
      run: terraform plan


