name: test
env:
    AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    
on:
  push:
    branches:
      - main
    

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Clon Rep
      uses: actions/checkout@v1

    # - name: echo
    #   run: cat var.AZURE_CLIENT_SECRET

    - uses: Azure/login@v1
      with:
        creds: '{"AZURE_CLIENT_ID","AZURE_CLIENT_SECRET","AZURE_SUBSCRIPTION_ID","AZURE_TENANT_ID"}'


    - name: terraform init
      run: terraform init

    - name: terraform plan
      run: terraform plan


